# Common variables
.pytango vars:
  variables:
    MODULE_PATH: docker/pytango/9.3.0/buster-slim
    IMAGE_NAME: pytango-9.3.0
    IMAGE_TAG: buster-slim

# Build on changes in branch
.when pytango changes:
  only:
    changes:
      - docker/pytango/**/*
    refs:
      - branches

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
build pytango when changes:
  extends:
    - .pytango vars
    - .docker-two-stage-build
    - .when pytango changes

build pytango when master:
  extends:
    - .pytango vars
    - .docker-two-stage-build
    - .when master

# -----------------------------------------------------------------------------
# Test build
# -----------------------------------------------------------------------------
.pytango tests:
  extends:
    - .pytango vars
    - .docker-test-image
  script:
    - python3 -c "import tango; assert tango.__version__ == '9.3.0'"

test build when changes:
  extends:
    - .pytango tests
    - .when pytango changes

test build when master:
  extends:
    - .pytango tests
    - .when master

# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
publish pytango when master:
  extends:
    - .docker-push-image
    - .pytango vars
    - .when master

publish pytango when manual:
  extends:
    - .docker-push-image
    - .pytango vars
  when: manual
