# Common variables
.pytango-9.3.0:buster-slim vars:
  variables:
    MODULE_PATH: docker/pytango/9.3.0/buster-slim
    IMAGE_NAME: pytango-9.3.0
    IMAGE_TAG: buster-slim

# Over-ride general behaviour of .when-docker-image-changes for module path
.when-pytango-changes:
  extends: .when-docker-image-changes
  only:
    changes:
      - docker/pytango/**/*

# Over-ride general behaviour of .when-docker-image-tagged for module path
.when-pytango-tagged:
  extends:
    - .when-docker-image-tagged
    - .pytango-9.3.0:buster-slim vars
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^$IMAGE_NAME==$IMAGE_TAG/

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
build pytango-9.3.0:buster-slim when changes:
  extends:
    - .docker-two-stage-build
    - .pytango-9.3.0:buster-slim vars
    - .when-pytango-changes

build pytango-9.3.0:buster-slim when tagged:
  extends:
    - .docker-two-stage-build
    - .pytango-9.3.0:buster-slim vars
    - .when-pytango-tagged


# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------
.pytango-9.3.0:buster-slim tests:
  extends:
    - .docker-test-image
    - .pytango-9.3.0:buster-slim vars
  script:
    - python3 -c "import tango; assert tango.__version__ == '9.3.0'"

test pytango-9.3.0:buster-slim when changes:
  extends:
    - .pytango-9.3.0:buster-slim tests
    - .when-pytango-changes

test pytango-9.3.0:buster-slim test whem tagged:
  extends:
    - .pytango-9.3.0:buster-slim tests
    - .when-pytango-tagged


# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
publish pytango-9.3.0:buster-slim when tagged:
  extends:
    - .docker-push-image
    - .pytango-9.3.0:buster-slim vars
    - .when-pytango-tagged
