
helm_deploy:
  container: pw410/helm-deploy
  version: 0.0.4
  replicas: 1

etcd:
  version: "3.3"
  replicas: 1

workflow:
  testdeploy:
    container: pw410/workflow-testdeploy
    version: 0.0.7
    replicas: 2
    resources: {}

nameOverride: ""
fullnameOverride: ""
