# Build and push `tangods_sdp_master` image.
build:tangods_sdp_master:
  extends: .build_docker
  variables:
    BUILD_PATH: src/tango_sdp_master

# Build and push `tangods_sdp_subarray` image.
build:tangods_sdp_subarray:
  extends: .build_docker
  variables:
    BUILD_PATH: src/tango_sdp_subarray
