push:pytango_build:
  extends: .push_docker
  dependencies:
    - build:pytango_build
  variables:
    BUILD_PATH: docker/pytango_build

push:pytango_base:
  extends: .push_docker
  dependencies:
    - build:pytango_base
  variables:
    BUILD_PATH: docker/pytango_base

push:pytango_ska_base:
  extends: .push_docker
  dependencies:
    - build:pytango_ska_base
  variables:
    BUILD_PATH: docker/pytango_ska_base

push:pytango_ska_dev:
  extends: .push_docker
  dependencies:
    - build:pytango_ska_dev
  variables:
    BUILD_PATH: docker/pytango_ska_dev

.tangods_master_template:
  extends: .push_docker
  when: always
  dependencies:
    - build:tangods_sdp_master
  variables:
    BUILD_PATH: src/tango_sdp_master

push:tangods_sdp_master:
  extends: .tangods_master_template
  only: [master]

push:tangods_sdp_master-manual:
  extends: .tangods_master_template
  when: manual
  except: [master]

