.push_docker:
  stage: publish
  variables:
    DOCKER_REGISTRY_HOST: $DOCKER_REGISTRY_HOST
    DOCKER_REGISTRY_USER: $CI_PROJECT_NAME
    GIT_VERSION: ${CI_COMMIT_SHA:0:8}
  tags:
    - docker
    - engageska
  when: manual
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add make git
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
  script:
    - cd $BUILD_PATH
    - make DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME pull_default
    - make DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME push_version
    - make DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME push_latest
  retry: 2

push:pytango_build:
  extends: .push_docker
  dependencies:
    - build:pytango_build
  variables:
    BUILD_PATH: docker/pytango_build

push:pytango_base:
  extends: .push_docker
  dependencies:
    - build:pytango_base
  variables:
    BUILD_PATH: docker/pytango_base

push:pytango_ska_base:
  extends: .push_docker
  dependencies:
    - build:pytango_ska_base
  variables:
    BUILD_PATH: docker/pytango_ska_base

push:pytango_ska_dev:
  extends: .push_docker
  dependencies:
    - build:pytango_ska_dev
  variables:
    BUILD_PATH: docker/pytango_ska_dev

.tangods_master_template:
  extends: .push_docker
  when: always
  dependencies:
    - build:tangods_sdp_master
  variables:
    BUILD_PATH: src/tango_sdp_master

push:tangods_sdp_master:
  extends: .tangods_master_template
  only: [master]

push:tangods_sdp_master-manual:
  extends: .tangods_master_template
  when: manual
  except: [master]

.tangods_subarray_template:
  extends: .push_docker
  when: always
  dependencies:
    - build:tangods_sdp_subarray
  variables:
    BUILD_PATH: src/tango_sdp_subarray

push:tangods_sdp_subarray:
  extends: .tangods_subarray_template
  only: [master]

push:tangods_sdp_subarray-manual:
  extends: .tangods_subarray_template
  when: manual
  except: [master]
