# Common variables
.pytango-vars: &pytango-vars
  variables:
    IMAGE_NAME: pytango-9.3.0
    IMAGE_TAG: buster-slim
    IMAGE_PATH: docker/pytango/9.3.0/buster-slim

# Logic for only running job if changes and not tag
.pytango-changes: &pytango-changes
  only:
    changes:
      - docker/pytango/9.3.0/buster-slim/Dockerfile
  except:
    refs:
      - tags

# Logic for only running job if tag
.pytango-tag: &pytango-tag
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^(pytango-9.3.0)/


# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
.pytango-9.3.0:buster-slim build:
  extends: .docker-two-stage-build
  <<: *pytango-vars

pytango-9.3.0:buster-slim build - changes:
  extends: .pytango-9.3.0:buster-slim build
  <<: *pytango-changes

pytango-9.3.0:buster-slim build - tag:
  extends: .pytango-9.3.0:buster-slim build
  <<: *pytango-tag

# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------
.pytango-9.3.0:buster-slim test:
  extends: .docker-test-image
  <<: *pytango-vars
  script:
    - echo "$CI_COMMIT_TAG"
    - echo "$CI_COMMIT_MESSAGE"
    - echo "$IMAGE_NAME"
    - cd $IMAGE_PATH
    - pip list
    - python3 -c "import tango; print(tango.__version__)"
    # TODO Test this image!

pytango-9.3.0:buster-slim test - changes:
  extends: .pytango-9.3.0:buster-slim test
  <<: *pytango-changes

pytango-9.3.0:buster-slim test - tag:
  extends: .pytango-9.3.0:buster-slim test
  <<: *pytango-tag

# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
pytango-9.3.0:buster-slim publish:
  extends: .docker-push-image
  <<: *pytango-vars
  <<: *pytango-tag
