publish:ska-sdp-master-manual:
  extends: .publish_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_master

publish:ska-sdp-master:
  extends: .publish_python_relase
  variables:
    BUILD_PATH: src/tango_sdp_master
