build:ska-sdp-master_dev:
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_master
  except: [master]

build:ska-sdp-master:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/tango_sdp_master
  only: [master]

build:ska-sdp-subarray_dev:
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/tango_sdp_subarray
  except: [master]

build:ska-sdp-subarray:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/tango_sdp_subarray
  only: [master]
