# Generate combined test coverage report
coverage_report:
  stage: post_test
  tags: [docker]
  image: python:latest
  before_script:
    - pip install coverage
  script:
    - coverage combine *.coverage
    - coverage report
    - coverage html
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths: [htmlcov/]
    expire_in: 1 week

# Create an XRay test execution report
# (currently only for the SDPSubarray tests)
.xray_report:
  stage: post_test
  tags: [docker]
  image: python:latest
  script:
    - 'curl -X POST -H "Content-Type: application/json"
         -H "Authorization: Basic $JIRA_AUTH"
         --data @cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 # In case JIRA doesn't work first time

# Update XRay links in JIRA automatically This is done only for the master
xray_report:
  extends: .xray_report
  only: [master]

# Update XRay links in JIRA. Manual job that can be executed for branches
xray_report-manual:
  extends: .xray_report
  when: manual
  except: [master]

# Build documentation
build_docs:
  stage: test
  when: manual
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - make -C docs html
  artifacts:
    paths: [docs/build/html/]
    expire_in: 1 day
