# -----------------------------------------------------------------------------
# (Initial) Test & linting stage
# -----------------------------------------------------------------------------

# Run linters and unit tests for the SDP Subarray device.
test subarray device:
  stage: test
  tags: [docker]
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango-orca-dev:0.3.0-buster-slim
  variables:
    MODULE_PATH: src/tango_sdp_subarray
  script:
    - cd $MODULE_PATH
    - make test
  after_script:
    - mv .coverage $CI_JOB_ID.coverage
  only:
    changes:
      - src/tango_sdp_subarray/**/*
  artifacts:
    paths:
      - cucumber.json
      - $CI_JOB_ID.coverage
    expire_in: 1 day


# -----------------------------------------------------------------------------
# Build Stage
# -----------------------------------------------------------------------------

# Build a test SDP Subarray device image.
build tangods_sdp_subarray image:
  stage: build
  tags:
    - docker
    - engageska
  image: docker:stable
  services:
    - docker:dind
  variables:
    MODULE_PATH: src/tango_sdp_subarray
    DOCKER_REGISTRY_HOST: $DOCKER_REGISTRY_HOST
    DOCKER_REGISTRY_USER: $CI_PROJECT_NAME
    DOCKER_REGISTRY_USERNAME: $DOCKER_REGISTRY_USERNAME
    DOCKER_REGISTRY_PASSWORD: $DOCKER_REGISTRY_PASSWORD
  before_script:
    - apk add make git
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
  script:
    - cd $MODULE_PATH
    - make docker-build-test-image
    - make docker-push-test-image
  only:
    changes:
      - src/tango_sdp_subarray/**/*


# -----------------------------------------------------------------------------
# Test Build Stage
# -----------------------------------------------------------------------------

test ska-sdp-subarray package:
  stage: test-build
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango-orca-dev:0.3.0-buster-slim
  tags:
    - docker
    - engageska
  variables:
    MODULE_PATH: src/tango_sdp_subarray
  script:
    - cd $MODULE_PATH
    - make python-test-package
  only:
    changes:
      - src/tango_sdp_subarray/**/*
  artifacts:
    paths:
      - ./$BUILD_PATH/dist/


#test tangods_sdp_subarray image:
#  stage: test-build
#  image: nexus.engageska-portugal.pt/sdp-prototype/tangods_sdp_subarray:0.2.2-buster-slim-test
# TODO(BMo) Test the docker image


# -----------------------------------------------------------------------------
# Publish Stage
# -----------------------------------------------------------------------------


push tangods_sdp_subarray image:
  stage: publish
  tags:
    - docker
    - engageska
  variables:
    GIT_STRATEGY: none
    IMAGE_NAME: tangods_sdp_subarray
    IMAGE_TAG: 0.3.0-buster-slim
    IMAGE: $DOCKER_REGISTRY_HOST/$CI_PROJECT_NAME/$IMAGE_NAME
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
  script:
    - docker pull $IMAGE:$IMAGE_TAG-test
    - docker tag $IMAGE:$IMAGE_TAG-test $IMAGE:$IMAGE_TAG
    - docker tag $IMAGE:$IMAGE_TAG-test $IMAGE:latest
    - docker image ls
    - docker push $IMAGE:$IMAGE_TAG
    - docker push $IMAGE:latest
  only:
    changes:
      - src/tango_sdp_subarray/**/*
#  only:
#    refs:
#      - tags
#    variables:
#      - $CI_COMMIT_TAG =~ /^(tangods_sdp_subarray==)((\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?|devel|dev|latest|stable|unstable)(.*)/

publish ska-sdp-subarray python package:
  stage: publish
  tags:
    - docker
    - engageska
  image: nexus.engageska-portugal.pt/sdp-prototype/pytango-orca-dev:0.3.0-buster-slim
  variables:
    MODULE_PATH: src/tango_sdp_subarray
    PACKAGE_NAME: ska-sdp-subarray
  script:
    - cd $MODULE_PATH
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true
    - twine upload --skip-existing -u $PYPI_USER -p $PYPI_PASS dist/* || true
#  only:
#    refs:
#      - tags
#    variables:
#      - $CI_COMMIT_TAG =~ /^(ska-sdp-subarray==)(\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?/
  only:
    changes:
      - src/tango_sdp_subarray/**/*
