# Common variables
.ska-lmc-baseclasses:devel-buster-slim vars:
  variables:
    MODULE_PATH: docker/ska-lmc-baseclasses/devel-buster-slim
    IMAGE_NAME: ska-lmc-baseclasses
    IMAGE_TAG: devel-buster-slim


# Over-ride general behaviour of .when-docker-image-changes for module path
.when ska-lmc-baseclasses changes:
  extends: .when-docker-image-changes
  only:
    changes:
      - docker/ska-lmc-baseclasses/**/*

# Over-ride general behaviour of .when-docker-image-tagged for module path
.when ska-lmc-baseclasses tagged:
  extends:
    - .when-docker-image-tagged
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^(ska-lmc-baseclasses==)((\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?|devel|dev|latest|stable|unstable)(-buster-slim)/


# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
build ska-lmc-baseclasses:devel-buster-slim when changes:
  extends:
    - .docker-two-stage-build
    - .ska-lmc-baseclasses:devel-buster-slim vars
    - .when ska-lmc-baseclasses changes

build ska-lmc-baseclasses:devel-buster-slim when tagged:
  extends:
    - .docker-two-stage-build
    - .ska-lmc-baseclasses:devel-buster-slim vars
    - .when ska-lmc-baseclasses tagged


# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------
.ska-lmc-baseclasses:devel-buster-slim tests:
  extends:
    - .docker-test-image
    - .ska-lmc-baseclasses:devel-buster-slim vars
  script:
#    - cd $MODULE_PATH
#    - pip list
    - python3 -c "import tango; assert tango.__version__ == '9.3.0'"
    - python3 -c "import skabase; print(skabase.__all__)"
    - python3 -c "from skabase import SKAMaster; print(SKAMaster.__version__)"

test ska-lmc-baseclasses:devel-buster-slim when changes:
  extends:
    - .ska-lmc-baseclasses:devel-buster-slim tests
    - .when ska-lmc-baseclasses changes

test ska-lmc-baseclasses:devel-buster-slim when tagged:
  extends:
    - .ska-lmc-baseclasses:devel-buster-slim tests
    - .when ska-lmc-baseclasses tagged


# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
publish ska-baseclasses:devel-buster-slim when tagged:
  extends:
  - .docker-push-image
  - .ska-lmc-baseclasses:devel-buster-slim vars
  - .when ska-lmc-baseclasses tagged
