---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-sdp-devices
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
data:
  sdp-devices.json:
{{ (tpl (.Files.Glob "data/sdp-devices.json").AsConfig . ) | indent 2  }}
  sane-dsconfig.sh:
{{ (tpl (.Files.Glob "data/sane-dsconfig.sh").AsConfig . ) | indent 2  }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sdp-devices
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sdp-prototype.fullname" . }}-sdp-devices
  template:
    metadata:
      labels:
        app: {{ include "sdp-prototype.fullname" . }}-sdp-devices
{{ include "sdp-prototype.labels" . | indent 8 }}
    spec:
      volumes:
        - name: configuration
          configMap:
            name: {{ include "sdp-prototype.fullname" . }}-sdp-devices
      initContainers:
        - name: dsconfig
          image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
          imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
          command:
            - /usr/local/bin/wait-for-it.sh
            - databaseds-tango-base-{{ .Release.Name }}:10000
            - --timeout=30
            - --strict
            - --
            - /bin/bash
            - data/sane-dsconfig.sh -w -a -u data/sdp-devices.json
          env:
            - name: TANGO_HOST
              value: databaseds-tango-base-{{ .Release.Name }}:10000
          volumeMounts:
            - name: configuration
              mountPath: data
              readOnly: true
      containers:
      - name: sdp-master
        env:
        - name: TANGO_HOST
          value: databaseds-tango-base-{{ .Release.Name }}:10000
        image: {{ .Values.tango.master.image }}:{{ .Values.tango.master.version }}
        imagePullPolicy: {{ .Values.tango.master.imagePullPolicy }}
        {{- with .Values.tango.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: sdp-subarray
        env:
        - name: TANGO_HOST
          value: databaseds-tango-base-{{ .Release.Name }}:10000
        - name: TOGGLE_CONFIG_DB
          value: "0"
        - name: TOGGLE_CBF_OUTPUT_LINK
          value: "0"
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.etcd-host" . }}
        image: {{ .Values.tango.subarray.image }}:{{ .Values.tango.subarray.version }}
        imagePullPolicy: {{ .Values.tango.subarray.imagePullPolicy }}
        {{- with .Values.tango.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
