apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-vis-receive
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.workflow.visreceive.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.workflow.visreceive.container }}:{{ .Values.workflow.visreceive.version }}
        imagePullPolicy: {{ .Values.workflow.visreceive.imagePullPolicy }}
        name: {{ .Chart.Name }}
        args: ["432", "4", "8", "8", "3", "41000", "4", "/app/output"]
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.fullname" . }}
        {{- with .Values.workflow.visreceive.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
