apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-workflow-visreceive
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.workflow.visreceive.replicas }}
  selector:
    matchLabels:
      app: {{ include "sdp-prototype.fullname" . }}-workflow-visreceive
  template:
    metadata:
      labels:
        app: {{ include "sdp-prototype.fullname" . }}-workflow-visreceive
{{ include "sdp-prototype.labels" . | indent 8 }}
    spec:
      initContainers:
      {{ include "sdp-prototype.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.workflow.visreceive.container }}:{{ .Values.workflow.visreceive.version }}
        imagePullPolicy: {{ .Values.workflow.visreceive.imagePullPolicy }}
        name: {{ .Chart.Name }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.etcd-host" . }}
        {{- with .Values.workflow.visreceive.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
