# Default values for vis_receive
# Declare variables to be passed into your templates.

visreceive:
  container: pw410/vis_receive
  version: 0.1.0
  replicas: 1
  resources: {}
  imagePullPolicy: IfNotPresent

vissender:
  container: pw410/vis_sender
  version: 0.1.0
  replicas: 1
  resources: {}
  imagePullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

