# Common variables
.pytango-9.3.0:buster-slim vars:
  variables:
    MODULE_PATH: docker/pytango/9.3.0/buster-slim
    IMAGE_NAME: pytango-9.3.0
    IMAGE_TAG: buster-slim

# Over-ride general behaviour of .when-docker-image-changes for module path
.when-pytango-changes:
  only:
    changes:
      - docker/pytango/**/*
  except:
    ref:
      - master

.when-pytango-master:
  only:
    ref:
      - master

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
build pytango-9.3.0:buster-slim when changes:
  extends:
    - .docker-two-stage-build
    - .pytango-9.3.0:buster-slim vars
    - .when-pytango-changes

build pytango-9.3.0:buster-slim when master:
  extends:
    - .docker-two-stage-build
    - .pytango-9.3.0:buster-slim vars
    - .when-pytango-master

# -----------------------------------------------------------------------------
# Test build
# -----------------------------------------------------------------------------
.pytango-9.3.0:buster-slim tests:
  extends:
    - .docker-test-image
    - .pytango-9.3.0:buster-slim vars
  script:
    - python3 -c "import tango; assert tango.__version__ == '9.3.0'"

test pytango-9.3.0:buster-slim when changes:
  extends:
    - .pytango-9.3.0:buster-slim tests
    - .when-pytango-changes

test pytango-9.3.0:buster-slim when master:
  extends:
    - .pytango-9.3.0:buster-slim tests
    - .when-pytango-master

# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
publish pytango-9.3.0:buster-slim when master:
  extends:
    - .docker-push-image
    - .pytango-9.3.0:buster-slim vars
    - .when-pytango-master

