# Common variables
.pytango-orca-dev:0.3.0-buster-slim vars:
  variables:
    MODULE_PATH: docker/pytango-orca-dev/0.3.0-buster-slim
    IMAGE_NAME: pytango-orca-dev
    IMAGE_TAG: 0.3.0-buster-slim

# Over-ride general behaviour of .when-docker-image-changes for module path
.when pytango-orca-dev changes:
  extends: .when-docker-image-changes
  only:
    changes:
      - docker/pytango-orca-dev/**/*

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
build pytango-orca-dev:0.3.0-buster-slim when changes:
  extends:
    - .docker-two-stage-build
    - .pytango-orca-dev:0.3.0-buster-slim vars
    - .when pytango-orca-dev changes

build pytango-orca-dev:0.3.0-buster-slim when tagged:
  extends:
    - .docker-two-stage-build
    - .pytango-orca-dev:0.3.0-buster-slim vars
    - .when-docker-image-tagged


# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------
.pytango-orca-dev:0.3.0-buster-slim tests:
  extends:
    - .docker-test-image
    - .pytango-orca-dev:0.3.0-buster-slim vars
  script:
#    - cd $MODULE_PATH
    - pip list
    - python3 -c "import tango; assert tango.__version__ == '9.3.0'"

test pytango-orca-dev:0.3.0-buster-slim when changes:
  extends:
    - .pytango-orca-dev:0.3.0-buster-slim tests
    - .when pytango-orca-dev changes


test pytango-orca-dev:0.3.0-buster-slim when tagged:
  extends:
    - .pytango-orca-dev:0.3.0-buster-slim tests
    - .when-docker-image-tagged


# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
publish pytango-orca-dev:0.3.0-buster-slim when tagged:
  extends:
    - .docker-push-image
    - .pytango-orca-dev:0.3.0-buster-slim vars
    - .when-docker-image-tagged
