# Common variables
.pytango-orca-dev  vars:
  variables:
    MODULE_PATH: docker/pytango-orca-dev/0.3.0-buster-slim
    IMAGE_NAME: pytango-orca-dev
    IMAGE_TAG: 0.3.0-buster-slim

# Build on changes in branch
.when pytango changes:
  only:
    changes:
      - docker/pytango/**/*
    refs:
      - branches

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------
build pytango-orca-dev:VERSION-buster-slim when changes:
  extends:
    - .docker-two-stage-build
    - .pytango-orca-dev vars
    - .when pytango-orca-dev changes

#build pytango-orca-dev:0.3.0-buster-slim when tagged:
#  extends:
#    - .docker-two-stage-build
#    - .pytango-orca-dev:0.3.0-buster-slim vars
#    - .when pytango-orca-dev tagged


# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------
.pytango-orca-dev:0.3.0-buster-slim tests:
  extends:
    - .docker-test-image
    - .pytango-orca-dev:0.3.0-buster-slim vars
  script:
#    - cd $MODULE_PATH
    - pip list
    - python3 -c "import tango; assert tango.__version__ == '9.3.0'"

test pytango-orca-dev:0.3.0-buster-slim when changes:
  extends:
    - .pytango-orca-dev:0.3.0-buster-slim tests
    - .when pytango-orca-dev changes


#test pytango-orca-dev:0.3.0-buster-slim when tagged:
#  extends:
#    - .pytango-orca-dev:0.3.0-buster-slim tests
#    - .when pytango-orca-dev tagged


# -----------------------------------------------------------------------------
# Publish / push
# -----------------------------------------------------------------------------
publish pytango-orca-dev:0.3.0-buster-slim when tagged:
  extends:
    - .docker-push-image
    - .pytango-orca-dev:0.3.0-buster-slim vars
    - .when pytango-orca-dev changes
